apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{KUBECTL_CERTIFICATE_AUTH}}
    server: {{KUBECTL_SERVER}}
  name: k3d-main-cluster
contexts:
- context:
    cluster: k3d-main-cluster
    user: admin@k3d-main-cluster
  name: k3d-main-cluster
current-context: k3d-main-cluster
kind: Config
preferences: {}
users:
- name: admin@k3d-main-cluster
  user:
    client-certificate-data: {{KUBECTL_CERTIFICATE_DATA}}
    client-key-data: {{KUBECTL_KEYT_DATA}}