name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
        name: Checkout do repositorio
      - name: Autenticação no Docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Construcao da Imagem Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            hayiu/devops4devs-news:latest
            hayiu/devops4devs-news:${{github.run_number}}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.2
        
      - name: Set up kubectl
        uses: Azure/setup-kubectl@v4.0.0

      - name: Update kubeconfig
        shell: bash
        run: |
          sed -i "s/{{KUBECTL_CERTIFICATE_AUTH}}/${{secrets.KUBECTL_CERTIFICATE_AUTH}}/g" ./kubeconfig.yaml
          sed -i "s/{{KUBECTL_SERVER}}/${{secrets.KUBECTL_SERVER}}/g" ./kubeconfig.yaml
          sed -i "s/{{KUBECTL_CERTIFICATE_DATA}}/${{secrets.KUBECTL_CERTIFICATE_DATA}}/g" ./kubeconfig.yaml
          sed -i "s/{{KUBECTL_KEYT_DATA}}/${{secrets.KUBECTL_KEYT_DATA}}/g" ./kubeconfig.yaml

      - name: Deploy to Kubernetes
        # kubectl apply -f ./k8s/kubernetes.yaml --validate=false
        run: |
           kubectl --kubeconfig=./kubeconfig.yaml get all
          
        
