name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
        name: Checkout do repositorio
      - name: Autenticação no Docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Construcao da Imagem Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            hayiu/devops4devs-news:latest
            hayiu/devops4devs-news:${{github.run_number}}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
        name: Checkout do repositorio
      - name: Conectar com o Kubernetes
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            ./k8s/kubernetes.yaml
          images: |
            hayiu/devops4devs-news:${{github.run_number}}
        
