name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Construcao da Imagem Docker
        run: echo "Docker build"
      - name: Publicar a imagem no Docker Hub
        run: echo "Docker Push"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Conectar com o Kubernetes
        run: echo "Configurações do Kubeconfig"
      - name: Executar o Deploy
        run: echo "Kubectl apply"
  start-container:
    runs-on: self-hosted
    services:
      docker:
        image: docker:latest
        options: --privileged  # Necessary for Docker to run inside a container
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Docker Container
        run: |
          docker run -d -p 8000:80 nginx
        
