name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
        name: Checkout do repositorio
      - name: Autenticação no Docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Construcao da Imagem Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            hayiu/devops4devs-news:latest
            hayiu/devops4devs-news:${{github.run_number}}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4.1.2

      - name: Kuberentes (k8s) cli - kubectl
        # You may pin to the exact commit or the version.
        # uses: actions-hub/kubectl@2d91cef8ad99cd6af41d678be32d7316c846fe48
        uses: actions-hub/kubectl@v1.24.0
        with:
          # Kubernetes configuration
          args: get all         
        
